version: "3.9"
name: ecosunrise
services:
  web:
    container_name: ecosunrise_wp
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - 15015:80
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', 'http://localhost:15015/');
        define('WP_HOME', 'http://localhost:15015/');
    volumes:
      - ./source/themes/:/var/www/html/wp-content/themes/
      - ./source/plugins/:/var/www/html/wp-content/plugins/
      - ./source/uploads/:/var/www/html/wp-content/uploads/
    networks:
      - ecosunrise_network
  db:
    container_name: ecosunrise_db
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - ecosunrise_network
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql/data/:/var/lib/mysql/
      - .docker/mysql/backup:/docker-entrypoint-initdb.d
  adminer:
    container_name: ecosunrise_adm
    image: adminer
    depends_on:
      - db
    networks:
      - ecosunrise_network
    ports:
      - 15014:8080
    environment:
      UPLOAD_LIMIT: 999M
networks:
  ecosunrise_network:
    driver: bridge
